In [2]:
import numpy as np
npa= np.array([1, 2, 3])
print(npa)


[1 2 3]


In [3]:
import numpy as np
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
import numpy as np
a=np.zeros(2)
print(a)


[0. 0.]


In [5]:
import numpy as np
a=np.ones(4)
print(a)


[1. 1. 1. 1.]


In [6]:
import numpy as np
ab=np.empty(4)
print(ab)


[1. 1. 1. 1.]


In [7]:
import numpy as np
a=np.arange(7)
print(a)


[0 1 2 3 4 5 6]


In [8]:
import numpy as np

a=np.array(9)

print("Print A= ",a)
b=np.array([10,20,30])
    
print("Print B= ", b)
addition= np.add(a,b)

print("After Addition =", addition)
    
sub=np.subtract(b,a)
    
print("After Subtraction =",sub)

mul=np.multiply (a,b)
    
print("After Multiplcation =",mul)
    
div=np.divide (b,a)
    
print("After Division =",div)

div1=np.divide (b,5)
    
print("After Division =",div1)


Print A=  9
Print B=  [10 20 30]
After Addition = [19 29 39]
After Subtraction = [ 1 11 21]
After Multiplcation = [ 90 180 270]
After Division = [1.11111111 2.22222222 3.33333333]
After Division = [2. 4. 6.]


In [9]:
#reciprocal

a= np.array([0.25,1.33,1,111])
    
print(a)
    
rec=np.reciprocal(a) 
print(rec)


[  0.25   1.33   1.   111.  ]
[4.         0.7518797  1.         0.00900901]


In [10]:
a=np.array([10,100,1000])
print(a)

pow=np.power(a,2)
print("after ^2 = ", pow)
   
b=np.array([2,3,1])
    
pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)
   


[  10  100 1000]
after ^2 =  [    100   10000 1000000]
after b array elements as ^ =  [    100 1000000    1000]


In [11]:
a= np.array ([10,20,30])
b= np.array ([3,5,7])
    
print("values of A=", a)
print("values of B=", b)
    
mm=np.mod(a,b)
    
rm=np.remainder(a,b)
    
print("values of MOD=", mm)
print("values of REMAINDER=", rm)


values of A= [10 20 30]
values of B= [3 5 7]
values of MOD= [1 0 2]
values of REMAINDER= [1 0 2]


In [12]:
a=np.array([-5.6j, 0.2j,11, 1+1j])
print(a)
    
print("real=",np.real(a))
    
print("imaginary=",np.imag(a))
    
print("Conjugate=", np.conj(a))


[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [13]:
a=np.array ([1.0,5.3,123,0.56,25.5,32])
print(a)
    
print("after rounding up=", np.around(a))
    
print("after rounding up to 1st decimal value =", np.around(a,decimals=1))


[  1.     5.3  123.     0.56  25.5   32.  ]
after rounding up= [  1.   5. 123.   1.  26.  32.]
after rounding up to 1st decimal value = [  1.    5.3 123.    0.6  25.5  32. ]


In [14]:
a=np.array ([1.0,-5.3,123,-0.56,25.5,32])
    
print(a)
    
print('\\n')
    
print(np.floor(a))
    
print(np.ceil(a))


[  1.    -5.3  123.    -0.56  25.5   32.  ]
\n
[  1.  -6. 123.  -1.  25.  32.]
[  1.  -5. 123.  -0.  26.  32.]


In [15]:
import numpy as np
a=np.arange(2,9,2)
print(a)


[2 4 6 8]


In [17]:
y = np.ones(2, dtype=int)
print(y)
    


[1 1]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)


[1 2 3 4 5 6 7 8]


In [19]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)
    
a=np.delete(a, 1)
print(a)


[1 2 3 4 5 6 7 8]
[1 3 4 5 6 7 8]


In [20]:
a = np.array([19, 22, 34, 14, 55, 76, 47, 8])
print(a)
a=np.sort(a)
print(a)


[19 22 34 14 55 76 47  8]
[ 8 14 19 22 34 47 55 76]


In [21]:
import numpy as np
    
arr = np.array([[1, 2, 3], [4, 5, 6]])
a=arr.ndim
print(arr) 
print("dimensions = ", a)


[[1 2 3]
 [4 5 6]]
dimensions =  2


In [22]:
import numpy as np
    
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 33], [44, 55, 66]]])
a=arr.ndim
b=arr.size
print(arr) 
print("dimensions = ", a)
print("size = ", b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
dimensions =  3
size =  12


In [23]:
import numpy as np
    
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print("dimension= ", a.ndim)
print(b)
print("dimension= ", b.ndim)
print(c)
print("dimension= ", c.ndim)
print(d)
print("dimension= ", d.ndim)


42
dimension=  0
[1 2 3 4 5]
dimension=  1
[[1 2 3]
 [4 5 6]]
dimension=  2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension=  3


In [24]:
import numpy as np
    
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
    
print(arr.shape) 
   


(2, 4)


In [25]:
a = np.arange(6)
print(a)
    
b = a.reshape(3,2)
print(b)


[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
